### PR TITLE
Stop excessive logging

### PR DESCRIPTION
**Pull request by rahularya50**
Aims to address #25 and #28 .

### CODE REVIEW

**Comment by rahularya50** [comment]
Todos from #25:
  - [ ] Implement a warning in the GUI that the debugger is disabled
  - [x] Disable logging server-side based on memory consumption
  - [x] Ensure that subsequent interaction with the console can still be debugged, even when previous code timed out.
  - [x] Disable the logging of the call stack at some point, since super long error tracebacks are meaningless anyway? But then the memory usage of the stack isn't significant anyway.
  - [ ] Possibly raise some sort of warning in the console, indicating that the debugger had to stop logging at some point? Maybe provide statistics?

**Comment by rahularya50** [comment]
Before, what happened was that whenever the saveState() function was called, the _entire_ client state was sent to the server to be stored, which caused frequent slowdowns. Now, saveState() takes a "full" parameter that is false by default. When full=false, saveState() will only save the state of the UI - i.e. windows, positions, state of debugger, console output, etc. - and not the full execution trace. So saveState(true) should only be called after program execution, or after a command is entered into the console.

However, this change makes interacting with the console much slowed, since a full saveState(true) call is made after every interaction. This should be fixed by reducing the size of the generated state itself on the server, which is what I'll implement next.

**Comment by rahularya50** [comment]
So, I just catch ImportErrors and ignore them, then disable the memory logging and print a warning. Not sure how else to fix this.

**Comment by rahularya50** [comment]
Currently fixes #25, #28.

**Comment by kavigupta** [comment]
OK I think we need to actually fix the import errors. Maybe we should move the checking memory usage to its own PR anyway?

**Comment by kavigupta** [comment]
This PR is too large IMO in any case

**Comment by rahularya50** [comment]
Split into #44, #45, and #46

**Pull request closed without merging**
