### PR TITLE
Turtle graphics

### LINKED ISSUE #57: Graphics
Make turtle graphics work.

### PR DESCRIPTION
**Pull request by rahularya50**
Implementing turtle graphics, fixes #57 .

### CODE REVIEW

**Comment by rahularya50** [comment]
List of primitives to implement / stub:

- [x] backward
- [x] begin_fill
- [x] bgcolor
- [x] circle
- [x] clear
- [x] color
- [x] end_fill
- [x] exitonclick
- [x] forward
- [x] hideturtle
- [x] left
- [x] pendown
- [x] pixel
- [x] pixelsize
- [x] rgb
- [x] right
- [x] screen_width
- [x] screen_height
- [x] setheading
- [x] setposition
- [x] showturtle
- [x] speed

**Comment by rahularya50** [comment]
~~Note that partial circle drawing isn't implemented (but that's also the case in scheme.cs61a.org rn)~~

Fixed by 620a1de

**Comment by rahularya50** [comment]
I'm not sure how to make the graphics accessible from the web interface. Should it just automatically open when graphics are drawn? But then when the user closes it, how can they reopen it?

Also, how should I implement `screen_width` / `screen_height`, since the canvas is zoomable in this version?

**Comment by kavigupta** [comment]
I can't tell where the turtle is initially

**Comment by kavigupta** [comment]
also it isn't centered?

**Comment by kavigupta** [comment]
It opens the turtle graphics instead of the console when you hit run, even if the editor contains no turtle commands

**Comment by rahularya50** [comment]
Right, I'm not sure what the desired behavior should be. In particular, if the graphics window opens, I draw something, then close the window, then draw something else, should it open again? And should this behavior depend on whether `(exitonclick)` is called?

Also, where should the graphics window go by default when it is created? Right now, I make it go in a tab adjacent to the output window, but I'm not sure that's the best idea?

**Comment by rahularya50** [comment]
One other thing - if I resize the turtle window drastically (like when dragging it around the window), the turtle sometimes goes offscreen. Should I reset the pan / zoom config when the svg is resized, or leave the current behavior as is?

**Comment by kavigupta** [comment]
> Right, I'm not sure what the desired behavior should be. In particular, if the graphics window opens, I draw something, then close the window, then draw something else, should it open again?
> 

let's just not do anything, just trust them to click the tab if they want

> Also, where should the graphics window go by default when it is created? Right now, I make it go in a tab adjacent to the output window, but I'm not sure that's the best idea?

maybe pop it up above when created?

**Comment by kavigupta** [comment]
> One other thing - if I resize the turtle window drastically (like when dragging it around the window), the turtle sometimes goes offscreen. Should I reset the pan / zoom config when the svg is resized, or leave the current behavior as is?

reset pan/zoom

**Comment by kavigupta** [comment]
also pls resolve conflicts

**Comment by rahularya50** [comment]
Conflicts resolved, I'll make it reset the pan/zoom now.

**Comment by rahularya50** [comment]
What do you mean by 
> pop it up above when created?

I can't create windows that pop-out of the browser, if that's what you mean.

**Pull request closed without merging**
