### PR TITLE
Definite improvement to javastyle front-end UI.

### PR DESCRIPTION
**Pull request by rahularya50**

### CODE REVIEW

**Review by kavigupta — CHANGES_REQUESTED** [review]
no

**Comment by rahularya50** [comment]
it has educational value

plus I now have the branch `improved-javastyle` permanently locked to this PR (right?) so no one can ever write a PR with that heretical name

**Comment by kavigupta** [comment]
nah I can just close the PR and delet the branch

**Comment by rahularya50** [comment]
try it

**Pull request closed without merging**
